### PR TITLE
Add hidden: true support to all APIs

### PR DESCRIPTION
**Pull request by mafintosh**
This PR adds a new option called hidden: true to .get, .del, .put, iterators, etc that allows you to insert a value in the trie that isn't returned by the normal .get / iterators.

This is useful for storing application specific metadata without having to reserve a character in the key.

It's implemented by setting the first bit in the hash to `1` if it's a hidden key (first bit is reserved atm for this usecase). It also stores a flag on the trie node itself to indicate that node is hidden so you know to flip that first bit when hashing it to traverse the trie properly.

/cc @andrewosh @pfrazee

### CODE REVIEW

**Comment by mafintosh** [comment]
(this will be a minor bump if we like it)

**Comment by pfrazee** [comment]
I'm sure this will be very useful. Some of my reactions:

I was surprised to see the hidden namespace is separate from the unhidden namespace. The idea that you could have a hidden and unhidden version of a file is kind of wild - it makes me wonder if "hidden" is the right word for it. It's more like a "shadow namespace."

One thing to consider is, compatibility with other filesystems. For instance, @mafintosh I was thinking about using the KV attributes to handle votes in the unwalled.garden spec, but realized that doing so would be incompatible with HTTP and with other filesystems, so I'd need a way to translate the information between them. For my usecase (vote records) it's just as easy to stick with filenames to encode that info.

Hidden files translate easily enough to existing filesystems if they share the namespace with unhidden files. If they have different namespaces, we'll need to come up with a way to translate between them.

**Comment by andrewosh** [comment]
@pfrazee One immediately useful feature that this enables is live files in Hyperdrive, which we're aiming to support in the next prerelease. With live files, you'd write a "live" Stat object at the beginning of the file write, and readers will assume that the file bounds extend to the current length of the content feed.

The issue there is that if the writer process crashes before the read completes, you'll wind up with a corrupted drive (the previous Stat is never finalized, so subsequent writes will fall within its bounds) -- a `.live` pointer in the trie will let us clean up an incomplete write when the drive is re-initialized.

Agreed about filesystem compatibility, though this API doesn't necessarily need to be exposed in Hyperdrive, at least not directly. Hidden files that obey filesystem semantics could also be done through unions, once those are supported.

**Comment by pfrazee** [comment]
> Hidden files that obey filesystem semantics could also be done through unions, once those are supported.

@andrewosh Are you referring to "union mounts" here?

**Comment by andrewosh** [comment]
@pfrazee Yeah, only to say that they'll open the door to experimenting more with permissions, visibility, and the like, without requiring any trie/schema changes. You could, for example, implement visibility by layering a hidden trie underneath the main trie.

Only bring it up to say that this particular feature need not necessarily be filesystem-compatible, though surely translating between this API and hidden files is also possible (can do an atomic write where you check if the non-hidden key exists before writing a hidden file, and aborting if so).

**Comment by andrewosh** [comment]
Was multiple files with the same name but different visibility your main concern about the separate namespaces? Might just be confused there

**Comment by mafintosh** [comment]
Ya hidden might not be the best word here. Private/internal perhaps? The intend here is not to expose this in Hyperdrive but add this to be able to add state to various algos you would want to add. Fx tracking mounts easily, or keeping track of authorized writers, etc etc.

**Comment by mafintosh** [comment]
(@pfrazee is cool with this, just talked with him)

**Comment by mafintosh** [comment]
3.4.0

**Comment by pfrazee** [comment]
Yeah that all makes sense, the overlapping namespaces was my only concern. I don't think changing the semantic is 100% necessary but `internal` might avoid the confusion. My assumption was that the trie had a near 1:1 with hyperdrive's files.

**Pull request merged**
